module.exports = [
  { comment: "Amazing place to stay with a calm and relaxing environment. The room was clean, comfortable, and well maintained throughout the visit.", rating: 5 },
  { comment: "Great experience overall. The surroundings were peaceful and the stay felt comfortable from check-in to check-out.", rating: 4 },
  { comment: "Very pleasant stay with clean rooms and a quiet atmosphere. It was perfect for relaxing and unwinding.", rating: 5 },
  { comment: "Nice location and comfortable setup. Everything was arranged properly and the stay was smooth.", rating: 4 },
  { comment: "The environment was calm and relaxing. Cleanliness and comfort were maintained very well.", rating: 5 },
  { comment: "Good experience overall. The room was neat, comfortable, and suitable for a peaceful stay.", rating: 4 },
  { comment: "Enjoyed the stay a lot. The calm surroundings and clean rooms made the experience enjoyable.", rating: 5 },
  { comment: "Decent stay overall. Everything was fine, but nothing felt extraordinary during the visit.", rating: 3 },
  { comment: "Comfortable and clean place to stay. The location was quiet and relaxing.", rating: 4 },
  { comment: "Very good experience. The room was well maintained and the atmosphere was peaceful.", rating: 5 },

  { comment: "Nice and relaxing stay. The environment was calm and the room was comfortable.", rating: 4 },
  { comment: "The stay was smooth and pleasant. Cleanliness and comfort were well taken care of.", rating: 5 },
  { comment: "Good place for a short break. Everything was clean and properly managed.", rating: 4 },
  { comment: "Comfortable stay with a peaceful atmosphere. The experience was satisfying overall.", rating: 4 },
  { comment: "Very relaxing experience. Clean surroundings and quiet location made it enjoyable.", rating: 5 },
  { comment: "The room was cozy and clean. The calm environment helped in relaxing properly.", rating: 4 },
  { comment: "Overall a good stay. The place was neat and comfortable for a short visit.", rating: 4 },
  { comment: "Nice experience with clean rooms and calm surroundings. Would consider staying again.", rating: 5 },
  { comment: "Average experience. The stay was comfortable but could be improved slightly.", rating: 3 },
  { comment: "Good and comfortable stay. Everything was as expected and well maintained.", rating: 4 },

  { comment: "Peaceful environment with clean rooms. The stay was relaxing and enjoyable.", rating: 5 },
  { comment: "Very comfortable stay with a calm atmosphere. Cleanliness was well maintained.", rating: 5 },
  { comment: "Nice and quiet place to stay. The experience was smooth and pleasant.", rating: 4 },
  { comment: "The stay was relaxing overall. Clean rooms and peaceful surroundings.", rating: 5 },
  { comment: "Good experience. The environment was calm and suitable for relaxation.", rating: 4 },
  { comment: "Comfortable stay with proper cleanliness. Everything felt organized and neat.", rating: 4 },
  { comment: "Enjoyed the peaceful location and comfortable room. A nice experience overall.", rating: 5 },
  { comment: "Decent stay. The room was clean but the experience was fairly average.", rating: 3 },
  { comment: "Nice place with a calm environment. The stay was comfortable and smooth.", rating: 4 },
  { comment: "Very pleasant experience. Clean and quiet surroundings made it enjoyable.", rating: 5 },

  { comment: "The stay was comfortable and peaceful. The room was clean and well maintained.", rating: 4 },
  { comment: "Good overall experience. Everything was clean and properly arranged.", rating: 4 },
  { comment: "Relaxing stay with calm surroundings. The room was neat and cozy.", rating: 5 },
  { comment: "Nice and peaceful location. The stay was comfortable and enjoyable.", rating: 4 },
  { comment: "The experience was very good. Cleanliness and comfort were top notch.", rating: 5 },
  { comment: "Comfortable stay overall. The calm environment made it relaxing.", rating: 4 },
  { comment: "Enjoyed the stay. The room was clean and the atmosphere was peaceful.", rating: 5 },
  { comment: "Average experience overall. The stay was fine but nothing special.", rating: 3 },
  { comment: "Good place to stay with clean rooms and calm surroundings.", rating: 4 },
  { comment: "Very relaxing stay. Everything was clean and properly maintained.", rating: 5 },

  { comment: "Peaceful and comfortable stay with clean rooms and a calm environment.", rating: 5 },
  { comment: "Nice experience overall. The stay was comfortable and well organized.", rating: 4 },
  { comment: "Clean rooms and quiet surroundings made the stay relaxing.", rating: 5 },
  { comment: "Good stay overall. The environment was calm and comfortable.", rating: 4 },
  { comment: "Very pleasant experience with clean and cozy rooms.", rating: 5 },
  { comment: "Comfortable and peaceful stay. Everything was well maintained.", rating: 4 },
  { comment: "Enjoyed the calm surroundings and clean room.", rating: 5 },
  { comment: "Decent stay. Comfortable but fairly standard experience.", rating: 3 },
  { comment: "Nice place with a peaceful atmosphere and clean rooms.", rating: 4 },
  { comment: "Good experience overall. The stay was relaxing and smooth.", rating: 5 },
];
