module.exports = [
  // 🦸 MARVEL (10)
  { username: "Tony_Stark", email: "tony.stark@starkindustries.com" },
  { username: "Steve_Rogers", email: "steve.rogers@avengers.com" },
  { username: "Bruce_Banner", email: "bruce.banner@avengers.com" },
  { username: "Natasha_Romanoff", email: "natasha.romanoff@shield.gov" },
  { username: "Peter_Parker", email: "peter.parker@dailybugle.com" },
  { username: "Thor_Odinson", email: "thor.odinson@asgard.com" },
  { username: "Loki_Laufeyson", email: "loki.laufeyson@asgard.com" },
  { username: "Wanda", email: "wanda.maximoff@avengers.com" },
  { username: "Stephen_Strange", email: "stephen.strange@sorcerer.supreme" },
  { username: "TChalla_Wakanda", email: "tchalla@wakanda.gov" },

  // 🐭 CARTOONS (15)
  { username: "Tom_Cat", email: "tom.cat@cartoonnetwork.com" },
  { username: "Jerry_Mouse", email: "jerry.mouse@cartoonnetwork.com" },
  { username: "Scooby_Doo", email: "scooby.doo@mysteryinc.com" },
  { username: "Shaggy_Rogers", email: "shaggy.rogers@mysteryinc.com" },
  { username: "Mickey_Mouse", email: "mickey.mouse@disney.com" },
  { username: "Donald_Duck", email: "donald.duck@disney.com" },
  { username: "Bugs_Bunny", email: "bugs.bunny@looneytunes.com" },
  { username: "Daffy_Duck", email: "daffy.duck@looneytunes.com" },
  { username: "SpongeBob", email: "spongebob@bikinibottom.tv" },
  { username: "Patrick_Star", email: "patrick.star@bikinibottom.tv" },
  { username: "Rick_Sanchez", email: "rick.sanchez@multiverse.tv" },
  { username: "Morty_Smith", email: "morty.smith@multiverse.tv" },
  { username: "Homer_Simpson", email: "homer.simpson@springfield.tv" },
  { username: "Bart_Simpson", email: "bart.simpson@springfield.tv" },
  { username: "Dora_Explorer", email: "dora.explorer@nickjr.com" },

  // 🐉 ANIME (15)
  { username: "Goku_Saiyan", email: "goku.saiyan@dragonball.anime" },
  { username: "Vegeta_Prince", email: "vegeta.prince@dragonball.anime" },
  { username: "Naruto_Uzumaki", email: "naruto.uzumaki@leafvillage.anime" },
  { username: "Sasuke_Uchiha", email: "sasuke.uchiha@leafvillage.anime" },
  { username: "Itachi_Uchiha", email: "itachi.uchiha@akatsuki.anime" },
  { username: "MonkeyDLuffy", email: "luffy.pirate@onepiece.anime" },
  { username: "Roronoa_Zoro", email: "zoro.swordsman@onepiece.anime" },
  { username: "Light_Yagami", email: "light.yagami@deathnote.anime" },
  { username: "Levi_Ackerman", email: "levi.ackerman@scouts.anime" },
  { username: "Eren_Yeager", email: "eren.yeager@paradis.anime" },
  { username: "Tanjiro_Kamado", email: "tanjiro.kamado@demonslayer.anime" },
  { username: "Gojo_Satoru", email: "gojo.satoru@jujutsu.anime" },
  { username: "Ichigo_Kurosaki", email: "ichigo.kurosaki@bleach.anime" },
  { username: "Edward_Elric", email: "edward.elric@alchemy.anime" },
  { username: "Mikasa_Ackerman", email: "mikasa.ackerman@scouts.anime" },

  // 🇮🇳 INDIAN SUPERHEROES / ICONIC (10)
  { username: "Shaktimaan", email: "shaktimaan@bharatshakti.in" },
  { username: "Krish_Rohit", email: "krish.rohit@jaadu.power" },
  { username: "Flying_Jatt", email: "flying.jatt@desipower.in" },
  { username: "Chitti_Robot", email: "chitti.robot@vaseegaran.ai" },
  { username: "RaOne", email: "raone@lucifer.game" },
  { username: "Bahubali", email: "bahubali@mahishmati.king" },
  { username: "Bhavesh_Joshi", email: "bhavesh.joshi@justice.india" },
  { username: "Krrish_Jaadu", email: "krrish@superpower.in" },
  { username: "Minnal_Murali", email: "minnal.murali@lightning.kerala" },
];
